name: verify task branch

on:
  push:
    branches-ignore:
      - "main"

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - run: cd react_frontend
      - run: npm install
      - run: npm run test

  try_build:
    needs: unit_test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - run: cd react_frontend
      - run: npm install
      - run: npm run build
